# Generated by Django 5.2 on 2025-05-12 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20)),
                ('dia', models.DateField()),
                ('hora', models.TimeField()),
                ('profesional', models.CharField(max_length=100)),
                ('asistida', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DatoSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('temperatura_corporal', models.FloatField()),
                ('temperatura_ambiental', models.FloatField()),
                ('bpm', models.IntegerField()),
                ('avg_bpm', models.IntegerField()),
                ('humedad', models.FloatField()),
                ('estado', models.CharField(default='Conectando', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Drogas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Educativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('tipsdia', models.CharField(blank=True, max_length=100, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('mensajeprevent', models.CharField(max_length=255)),
                ('mensajetexto', models.CharField(max_length=255)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='educativos/')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EncuestaRespondida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_encuesta', models.IntegerField()),
                ('cedula_usuario', models.CharField(max_length=20)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='foro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('fechapub', models.DateTimeField(auto_now_add=True)),
                ('fechaact', models.DateTimeField(auto_now_add=True)),
                ('tema', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaIrracional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ReferenciaCIE10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.CharField(max_length=50)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='temaforo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.IntegerField()),
                ('fechapub', models.DateTimeField(auto_now_add=True)),
                ('fechaact', models.DateTimeField(auto_now_add=True)),
                ('tema', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('contraseña', models.CharField(blank=True, max_length=100, null=True)),
                ('fechanacimiento', models.CharField(blank=True, max_length=100, null=True)),
                ('tipoa', models.CharField(choices=[('Participante', 'Participante'), ('Profesional', 'Profesional'), ('Administrador', 'Administrador'), ('Investigador', 'Investigador')], max_length=20)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreguntaEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_encuesta', models.IntegerField()),
                ('numero_pregunta', models.PositiveSmallIntegerField()),
                ('pregunta', models.TextField()),
                ('tipo_pregunta', models.CharField(choices=[('OMM', 'Opción múltiple con múltiples respuestas'), ('OMU', 'Opción múltiple con única respuesta'), ('OMMC', 'Opción múltiple con múltiples respuestas columna'), ('OMUC', 'Opción múltiple con única respuesta columna'), ('OMMV', 'Opción múltiple con múltiples respuestas vertical'), ('OMUV', 'Opción múltiple con única respuesta Vertical'), ('AB', 'Pregunta abierta'), ('VF', 'Verdadero o falso'), ('PRP', 'Pregunta relacion proporcionales')], max_length=8)),
                ('puntaje_pregunta', models.FloatField()),
                ('numero_opciones_respuesta', models.PositiveSmallIntegerField(default=0)),
                ('posible_respuesta_1', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_1', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_2', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_2', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_3', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_3', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_4', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_4', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_5', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_5', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_6', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_6', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_7', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_7', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_8', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_8', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_9', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_9', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_10', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_10', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_11', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_11', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_12', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_12', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_13', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_13', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_14', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_14', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_15', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_15', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_16', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_16', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_17', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_17', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_18', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_18', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_19', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_19', models.FloatField(blank=True, null=True)),
                ('posible_respuesta_20', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_respuesta_20', models.FloatField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('numero_encuesta', 'numero_pregunta')},
            },
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('puntaje_obtenido', models.FloatField(blank=True, null=True)),
                ('encuesta_respondida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='myapp.encuestarespondida')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.preguntaencuesta')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='myapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaEnContra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_en_contra', to='myapp.tipoidea')),
            ],
        ),
        migrations.CreateModel(
            name='PruebaAFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pruebas_a_favor', to='myapp.tipoidea')),
            ],
        ),
        migrations.CreateModel(
            name='Provoca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provoca', to='myapp.tipoidea')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaRealista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ideas_realistas', to='myapp.tipoidea')),
            ],
        ),
        migrations.CreateModel(
            name='historialmed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iniciotrat', models.DateField(blank=True, null=True)),
                ('ultimocon', models.DateField(blank=True, null=True)),
                ('recaidas', models.FloatField(blank=True, null=True)),
                ('diagnostico', models.CharField(max_length=100)),
                ('profesional', models.CharField(blank=True, max_length=100, null=True)),
                ('consumo', models.ManyToManyField(related_name='historiales', to='myapp.drogas')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='EIdeaIrracional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=200)),
                ('provoca', models.TextField()),
                ('pruebas_a_favor', models.TextField()),
                ('pruebas_en_contra', models.TextField()),
                ('utilidad', models.TextField()),
                ('idea_realista', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Usuariosparticipantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=100, unique=True)),
                ('correo1', models.CharField(blank=True, max_length=100, null=True)),
                ('correo2', models.CharField(blank=True, max_length=100, null=True)),
                ('estciv', models.CharField(choices=[('0', 'Soltero'), ('1', 'Casado'), ('2', 'Divorciado'), ('3', 'union libre'), ('4', 'viudo')], max_length=100)),
                ('sexo', models.CharField(choices=[('0', 'Mujer'), ('1', 'Hombre')], max_length=100)),
                ('contactoE1', models.CharField(default='N/A', max_length=255)),
                ('NumConE1', models.CharField(blank=True, max_length=100, null=True)),
                ('citas_asistidas', models.FloatField(blank=True, null=True)),
                ('citas_inasistidas', models.FloatField(blank=True, null=True)),
                ('recuperacion', models.IntegerField(default=0)),
                ('Nencuestashechas', models.FloatField(blank=True, default=0, null=True)),
                ('encuestas_hechas', models.ManyToManyField(blank=True, related_name='realizadas_por', to='myapp.encuesta')),
                ('encuestas_pendientes', models.ManyToManyField(blank=True, related_name='pendientes_para', to='myapp.encuesta')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Utilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilidades', to='myapp.tipoidea')),
            ],
        ),
    ]
