# Generated by Django 5.2 on 2025-05-13 22:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_usuarios_preguntas_usuarios_spreguntas'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroSensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=50)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('humedad', models.FloatField()),
                ('temperatura_ambiente', models.FloatField()),
                ('temperatura_corporal', models.FloatField()),
                ('avg_bpm', models.FloatField()),
            ],
        ),
    ]
