# Generated by Django 5.2.1 on 2025-05-23 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_datosensor_device_datosensor_userid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="datosensor",
            name="userId",
        ),
    ]
