# Generated by Django 5.2.1 on 2025-05-23 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0005_remove_datosensor_userid"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConnectionSensor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("device", models.CharField(default=None, max_length=50)),
                ("userId", models.CharField(default=None, max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("temperatura_corporal", models.FloatField()),
                ("temperatura_ambiental", models.FloatField()),
                ("bpm", models.IntegerField()),
                ("avg_bpm", models.IntegerField()),
                ("humedad", models.FloatField()),
                ("estado", models.CharField(default="Conectando", max_length=50)),
            ],
        ),
    ]
